Fullscreen = false
FullscreenDelay = "200ms"

FadeDelay = "1s"
FadeSpeed = 2

[Clock]
Enabled = true

[Walltaker]
Enabled = false
LinkID = 1
APIKey = "asdf"
CheckInterval = "15s"

[Walltaker.MaxSize]
Width = 1920
Height = 1080

[Control]
Enabled = true
